name: games_services
description: A new Flutter plugin to support game center and google play games services.
version: 4.0.1
homepage: https://github.com/Abedalkareem/games_services
repository: https://github.com/Abedalkareem/games_services
issue_tracker: https://github.com/Abedalkareem/games_services/issues

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter

  games_services_platform_interface:
    git:
      url: git@github.com:ufi-app/games_services.git
      path: games_services_platform_interface
      ref: 7bb2d2201d646cb1760e726be45f95bde40b3bc7
  
dev_dependencies:
  flutter_lints: ^2.0.1
  
flutter:
  plugin:
    platforms:
      android:
        package: com.abedalkareem.games_services
        pluginClass: GamesServicesPlugin
      ios:
        pluginClass: SwiftGamesServicesPlugin
        sharedDarwinSource: true
      macos:
        pluginClass: SwiftGamesServicesPlugin
        sharedDarwinSource: true
